# Generated by Django 5.1.6 on 2025-02-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tableofcontent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tableofcontent',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='topic_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='ContentAttachment',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='TableOfContent',
        ),
    ]
