# Generated by Django 5.1.6 on 2025-02-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_coursematerial_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
