# Generated by Django 5.1.6 on 2025-03-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='edited',
        ),
    ]
